### ISSUE TITLE
Documentation not clear enough

### ISSUE THREAD

**Issue by YonatanShaham** [HarelM/IHMMapboxMapExample#2]
Hello,

Unfortunately, the [documentation](https://github.com/HarelM/IHMMapboxMapExample/blob/main/README.md) is not clear about several points:

1. What should be the reference system of the geojson file? I guess WGS 84, but it does not say.
2. Where should the CORS-enabled link point to? To the geojson file or to the repo contain it plus the style file?
3. How to generate a style file and what is the style file format? Can there be a reference to a guide about that (assuming it's not IHM unique)?

I tried to create a layer with this repo and these links:

1. https://github.com/YonatanShaham/Fires
2. https://github.com/YonatanShaham/Fires/blob/main/Fires%20WGS84.geojson
3. https://rawcdn.githack.com/YonatanShaham/Fires/589c3171aa62a5695bb53452320ca87b0a1ffd7c/Fires%20WGS84.geojson?fbclid=IwAR2XSDCW5HqJwvWUV1NVynOwLI7n2H4EsM6YR9UZiHbWIkMZdrOnJGIE48I

**Comment by HarelM** [comment]
Great questions!
Once we figure out together how to do it please send a PR with changes to documentation so it will be clearer.
1. Yes wgs84
2. Both geojson and style file should be CORS enabled
3. A style file defined by maplibre style specification: https://maplibre.org/maplibre-gl-js-docs/style-spec/

The example file can be a good starting point.
The link to the style.json file is the link that should be used in IHM site when adding a custom layer.
Hope this helps... :-)

**Comment by YonatanShaham** [comment]
Thanks a lot!

Regarding #2: the UI dialogue asks for only one link address. So It's not clear to me how to link the style file. See image.

![image](https://user-images.githubusercontent.com/20026954/135630425-d9833bf6-76ef-4cb9-a19b-99a6c0782ba5.png)

**Comment by HarelM** [comment]
You need to reference the style file, either by githack or the raw address of github.
This one for this repo for example:
https://raw.githubusercontent.com/HarelM/IHMMapboxMapExample/main/style.json

**Comment by YonatanShaham** [comment]
Yes, got it eventually.

Have initial success: https://raw.githack.com/YonatanShaham/Fires/main/style.json

**Comment by HarelM** [comment]
Can you send a pull request with update to the docs? Information that might help others in the future?

**Comment by YonatanShaham** [comment]
Will do.

**Comment by HarelM** [comment]
Thanks for the PR!
I've also added a few lines of explanation as well...
Good luck with the fires stuff! :-)
